"""empty message

Revision ID: ae4e8a375b36
Revises: 3eb4d68df1fc
Create Date: 2020-08-03 04:03:36.435785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4e8a375b36'
down_revision = '3eb4d68df1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('comment', table_name='comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('comment', 'comment', ['comment'], unique=True)
    # ### end Alembic commands ###
