"""empty message

Revision ID: d1ff0c420e23
Revises: ae4e8a375b36
Create Date: 2020-08-06 19:08:06.137740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ff0c420e23'
down_revision = 'ae4e8a375b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('firstName', table_name='user')
    op.drop_index('lastName', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('lastName', 'user', ['lastName'], unique=True)
    op.create_index('firstName', 'user', ['firstName'], unique=True)
    # ### end Alembic commands ###
